# Generated by Django 5.2 on 2025-09-20 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_fileupload_message_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_codes',
                'indexes': [models.Index(fields=['user'], name='email_verif_user_id_bdc74d_idx'), models.Index(fields=['code'], name='email_verif_code_e4a811_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_42d424_idx'), models.Index(fields=['is_used'], name='email_verif_is_used_c5fa14_idx')],
            },
        ),
    ]
