# Generated by Django 5.2 on 2025-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='token_type',
            field=models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], default='access', max_length=10),
        ),
    ]
