# Generated by Django 5.2 on 2025-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usersession_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_status', 'Application Status'), ('new_application', 'New Application'), ('pitch', 'Business Pitch'), ('general', 'General Notification')], max_length=50),
        ),
    ]
