# Generated by Django 5.2.6 on 2025-09-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
