# Generated by Django 5.2.6 on 2025-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_usersession_user_delete_emailverificationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.CharField(choices=[('saas', 'SaaS'), ('ecommerce', 'E-commerce'), ('agency', 'Agency'), ('legal', 'Legal'), ('marketplace', 'Marketplace'), ('media', 'Media'), ('platform', 'Platform'), ('real_estate', 'Real Estate'), ('robotics', 'Robotics'), ('software', 'Software'), ('web3', 'Web3'), ('crypto', 'Crypto'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
