# Generated by Django 5.2.6 on 2025-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_startup_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('startup', 'applicant')},
        ),
        migrations.AddField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True),
        ),
    ]
