# Generated by Django 5.0.4 on 2025-11-12 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_application_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="embedding_model",
            field=models.CharField(
                blank=True, default="all-MiniLM-L6-v2", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="embedding_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="startup",
            name="embedding_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="startup",
            name="profile_embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="embedding_model",
            field=models.CharField(
                blank=True, default="all-MiniLM-L6-v2", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="embedding_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="embedding_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_compensation_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_work_modes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="RecommendationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("developer_startup", "Developer → Startup"),
                            ("founder_developer", "Founder → Developer"),
                            ("founder_startup", "Founder → Startup"),
                            ("investor_startup", "Investor → Startup"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("content_based", "Content-Based"),
                            ("als", "ALS Collaborative Filtering"),
                            ("two_tower", "Two-Tower Deep Learning"),
                            ("ranker", "Ranking Model"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("training_config", models.JSONField(blank=True, default=dict)),
                ("performance_metrics", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("trained_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendation_models",
                "indexes": [
                    models.Index(
                        fields=["use_case", "model_type", "is_active"],
                        name="recommendat_use_cas_7e19e8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StartupTrendingMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("popularity_score", models.FloatField(default=0.0)),
                ("trending_score", models.FloatField(default=0.0)),
                ("view_count_24h", models.IntegerField(default=0)),
                ("view_count_7d", models.IntegerField(default=0)),
                ("view_count_30d", models.IntegerField(default=0)),
                ("application_count_24h", models.IntegerField(default=0)),
                ("application_count_7d", models.IntegerField(default=0)),
                ("application_count_30d", models.IntegerField(default=0)),
                ("favorite_count_7d", models.IntegerField(default=0)),
                ("interest_count_7d", models.IntegerField(default=0)),
                ("active_positions_count", models.IntegerField(default=0)),
                ("velocity_score", models.FloatField(default=0.0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "startup",
                    models.OneToOneField(
                        db_column="startup_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_metrics",
                        to="api.startup",
                    ),
                ),
            ],
            options={
                "db_table": "startup_trending_metrics",
                "indexes": [
                    models.Index(
                        fields=["startup"], name="startup_tre_startup_13e800_idx"
                    ),
                    models.Index(
                        fields=["-popularity_score"],
                        name="startup_tre_popular_26587b_idx",
                    ),
                    models.Index(
                        fields=["-trending_score"],
                        name="startup_tre_trendin_4b3c0a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("click", "Click"),
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("favorite", "Favorite"),
                            ("apply", "Apply"),
                            ("interest", "Interest"),
                        ],
                        max_length=30,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        db_column="position_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.position",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        db_column="startup_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="api.startup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_interactions",
                "indexes": [
                    models.Index(
                        fields=["user", "startup", "created_at"],
                        name="user_intera_user_id_5e348c_idx",
                    ),
                    models.Index(
                        fields=["startup", "created_at"],
                        name="user_intera_startup_ef849f_idx",
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="user_intera_interac_516669_idx",
                    ),
                    models.Index(
                        fields=["position"], name="user_intera_positio_8f13c5_idx"
                    ),
                ],
                "unique_together": {("user", "startup", "interaction_type")},
            },
        ),
        migrations.CreateModel(
            name="UserOnboardingPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selected_categories", models.JSONField(blank=True, default=list)),
                ("selected_fields", models.JSONField(blank=True, default=list)),
                ("selected_tags", models.JSONField(blank=True, default=list)),
                (
                    "preferred_startup_stages",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "preferred_engagement_types",
                    models.JSONField(blank=True, default=list),
                ),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_onboarding_preferences",
                "indexes": [
                    models.Index(fields=["user"], name="user_onboar_user_id_69ed72_idx")
                ],
            },
        ),
    ]
