# Generated by Django 5.0.4 on 2025-11-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_startup_embedding_model_startup_embedding_updated_at_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="embedding_needs_update",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["embedding_needs_update"], name="users_embeddi_63b6cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["embedding_updated_at"], name="users_embeddi_08930a_idx"
            ),
        ),
    ]
