# Generated by Django 5.0.4 on 2025-11-12 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_add_embedding_needs_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("use_case", models.CharField(max_length=50)),
                ("recommendation_method", models.CharField(max_length=50)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("recommendations_shown", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("total_interactions", models.IntegerField(db_index=True, default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_dislikes", models.IntegerField(default=0)),
                ("total_applies", models.IntegerField(default=0)),
                ("ctr", models.FloatField(db_index=True, default=0.0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                (
                    "metrics_computed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("etl_processed", models.BooleanField(db_index=True, default=False)),
                ("etl_processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recommendation_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["created_at", "interaction_type"],
                name="user_intera_created_235262_idx",
            ),
        ),
        migrations.AddField(
            model_name="recommendationsession",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["user_id", "created_at"], name="recommendat_user_id_19356b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["use_case", "created_at"], name="recommendat_use_cas_39ad70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["recommendation_method"], name="recommendat_recomme_c8230f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["created_at", "use_case"], name="recommendat_created_7ae51d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["etl_processed", "created_at"],
                name="recommendat_etl_pro_51f1b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["use_case", "metrics_computed_at"],
                name="recommendat_use_cas_5619db_idx",
            ),
        ),
    ]
