# Generated by Django 5.0.4 on 2025-11-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_recommendationsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="embedding_needs_update",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="startup",
            index=models.Index(
                fields=["embedding_needs_update"], name="startups_embeddi_21541b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="startup",
            index=models.Index(
                fields=["embedding_updated_at"], name="startups_embeddi_d115df_idx"
            ),
        ),
    ]
