# Generated by Django 5.2.8 on 2025-11-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_useronboardingpreferences_investor_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="startuptrendingmetrics",
            name="last_decay_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="startuptrendingmetrics",
            name="last_interaction_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="recommendation_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="recommendation_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="recommendation_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="recommendation_session",
            field=models.ForeignKey(
                blank=True,
                db_column="recommendation_session_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interaction_events",
                to="api.recommendationsession",
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="recommendation_source",
            field=models.CharField(
                blank=True,
                choices=[("organic", "Organic"), ("recommendation", "Recommendation")],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="value_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["recommendation_session", "created_at"],
                name="idx_interaction_session_time",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["recommendation_source", "created_at"],
                name="idx_interaction_source_time",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "interaction_type", "created_at"],
                name="idx_interaction_user_type_time",
            ),
        ),
    ]
