# Generated by Django 5.0.4 on 2025-11-18 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_add_interaction_rank_score_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("click", "Click"),
                            ("contact", "Contact"),
                            ("apply_received", "Apply Received"),
                        ],
                        max_length=30,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("value_score", models.FloatField(db_index=True, default=0.0)),
                (
                    "recommendation_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("organic", "Organic"),
                            ("recommendation", "Recommendation"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("recommendation_rank", models.IntegerField(blank=True, null=True)),
                ("recommendation_score", models.FloatField(blank=True, null=True)),
                (
                    "recommendation_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "startup_interactions",
            },
        ),
        migrations.AddField(
            model_name="recommendationsession",
            name="startup_id",
            field=models.ForeignKey(
                blank=True,
                db_column="startup_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_sessions",
                to="api.startup",
            ),
        ),
        migrations.AlterField(
            model_name="recommendationmodel",
            name="use_case",
            field=models.CharField(
                choices=[
                    ("developer_startup", "Developer → Startup"),
                    ("investor_startup", "Investor → Startup"),
                    ("startup_developer", "Startup → Developer"),
                    ("startup_investor", "Startup → Investor"),
                    ("founder_developer", "Founder → Developer"),
                    ("founder_startup", "Founder → Startup"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recommendationsession",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationsession",
            index=models.Index(
                fields=["startup_id", "created_at"],
                name="recommendat_startup_57faa5_idx",
            ),
        ),
        migrations.AddField(
            model_name="startupinteraction",
            name="recommendation_session",
            field=models.ForeignKey(
                blank=True,
                db_column="recommendation_session_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startup_interaction_events",
                to="api.recommendationsession",
            ),
        ),
        migrations.AddField(
            model_name="startupinteraction",
            name="startup",
            field=models.ForeignKey(
                db_column="startup_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_interactions",
                to="api.startup",
            ),
        ),
        migrations.AddField(
            model_name="startupinteraction",
            name="target_user",
            field=models.ForeignKey(
                db_column="target_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_startup_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["startup", "target_user", "created_at"],
                name="startup_int_startup_14863b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["target_user", "created_at"],
                name="startup_int_target__7fa7d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["interaction_type"], name="startup_int_interac_feacaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["created_at", "interaction_type"],
                name="startup_int_created_8c11d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["recommendation_session", "created_at"],
                name="idx_startup_int_session",
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["recommendation_source", "created_at"],
                name="idx_startup_int_source",
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["startup", "interaction_type", "created_at"],
                name="idx_startup_int_type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="startupinteraction",
            unique_together={("startup", "target_user", "interaction_type")},
        ),
    ]
