# Generated by Django 5.0.4 on 2025-11-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_add_startup_interaction_and_reverse_sessions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="startupinteraction",
            new_name="idx_startup_int_session_time",
            old_name="idx_startup_int_session",
        ),
        migrations.RenameIndex(
            model_name="startupinteraction",
            new_name="idx_startup_int_source_time",
            old_name="idx_startup_int_source",
        ),
        migrations.RenameIndex(
            model_name="startupinteraction",
            new_name="idx_startup_int_type_time",
            old_name="idx_startup_int_type",
        ),
        migrations.RemoveField(
            model_name="startupinteraction",
            name="value_score",
        ),
        migrations.AlterField(
            model_name="recommendationmodel",
            name="use_case",
            field=models.CharField(
                choices=[
                    ("developer_startup", "Developer → Startup"),
                    ("founder_developer", "Founder → Developer"),
                    ("founder_startup", "Founder → Startup"),
                    ("investor_startup", "Investor → Startup"),
                    ("startup_developer", "Startup → Developer"),
                    ("startup_investor", "Startup → Investor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="startupinteraction",
            index=models.Index(
                fields=["startup", "created_at"], name="startup_int_startup_28b945_idx"
            ),
        ),
    ]
