from django.core.management.base import BaseCommand
from django.utils import timezone
import json
from api.models import User, Startup
from api.messaging_models import UserProfile
from api.recommendation_models import UserOnboardingPreferences


class Command(BaseCommand):
    help = 'Generate embeddings for users and startups (placeholder - requires sentence-transformers)'

    def add_arguments(self, parser):
        parser.add_argument(
            '--users',
            action='store_true',
            help='Generate embeddings for users',
        )
        parser.add_argument(
            '--startups',
            action='store_true',
            help='Generate embeddings for startups',
        )
        parser.add_argument(
            '--all',
            action='store_true',
            help='Generate embeddings for all users and startups',
        )

    def handle(self, *args, **options):
        self.stdout.write(self.style.WARNING(
            'Embedding generation requires sentence-transformers library.\n'
            'This is a placeholder command. Install sentence-transformers and implement actual embedding generation.'
        ))
        
        if options['all'] or options['users']:
            self.stdout.write(self.style.SUCCESS('Generating user embeddings...'))
            users = User.objects.filter(is_active=True)
            count = 0
            for user in users:
                # Build profile text for embedding
                profile_text_parts = []
                
                # Get user profile
                try:
                    profile = user.profile
                    if profile.bio:
                        profile_text_parts.append(profile.bio)
                    if profile.skills:
                        profile_text_parts.append(f"Skills: {', '.join(profile.skills)}")
                    if profile.experience:
                        exp_text = json.dumps(profile.experience) if isinstance(profile.experience, list) else str(profile.experience)
                        profile_text_parts.append(f"Experience: {exp_text}")
                    if profile.location:
                        profile_text_parts.append(f"Location: {profile.location}")
                except UserProfile.DoesNotExist:
                    pass
                
                # Get onboarding preferences
                try:
                    prefs = user.onboarding_preferences
                    if prefs.selected_categories:
                        profile_text_parts.append(f"Categories: {', '.join(prefs.selected_categories)}")
                    if prefs.selected_fields:
                        profile_text_parts.append(f"Fields: {', '.join(prefs.selected_fields)}")
                    if prefs.preferred_skills:
                        profile_text_parts.append(f"Preferred Skills: {', '.join(prefs.preferred_skills)}")
                except UserOnboardingPreferences.DoesNotExist:
                    pass
                
                # Add role
                profile_text_parts.append(f"Role: {user.role}")
                
                profile_text = ' '.join(profile_text_parts)
                
                # TODO: Generate actual embedding using sentence-transformers
                # from sentence_transformers import SentenceTransformer
                # model = SentenceTransformer('all-MiniLM-L6-v2')
                # embedding = model.encode(profile_text)
                # user.profile_embedding = json.dumps(embedding.tolist())
                
                # For now, just mark as needing update
                # user.profile_embedding = None  # Will be generated by Flask app
                user.embedding_updated_at = timezone.now()
                user.save(update_fields=['embedding_updated_at'])
                count += 1
            
            self.stdout.write(self.style.SUCCESS(f'Processed {count} users'))
        
        if options['all'] or options['startups']:
            self.stdout.write(self.style.SUCCESS('Generating startup embeddings...'))
            startups = Startup.objects.filter(status='active')
            count = 0
            for startup in startups:
                # Build startup text for embedding
                startup_text_parts = [startup.description]
                startup_text_parts.append(f"Field: {startup.field}")
                startup_text_parts.append(f"Category: {startup.category}")
                
                if startup.stages:
                    stages_text = ', '.join(startup.stages) if isinstance(startup.stages, list) else str(startup.stages)
                    startup_text_parts.append(f"Stages: {stages_text}")
                
                # Add tags
                tags = startup.tags.values_list('tag', flat=True)
                if tags:
                    startup_text_parts.append(f"Tags: {', '.join(tags)}")
                
                # Add position requirements
                positions = startup.positions.filter(is_active=True)
                for pos in positions:
                    if pos.description:
                        startup_text_parts.append(f"{pos.title}: {pos.description}")
                    if pos.requirements:
                        startup_text_parts.append(f"Requirements: {pos.requirements}")
                
                startup_text = ' '.join(startup_text_parts)
                
                # TODO: Generate actual embedding using sentence-transformers
                # from sentence_transformers import SentenceTransformer
                # model = SentenceTransformer('all-MiniLM-L6-v2')
                # embedding = model.encode(startup_text)
                # startup.profile_embedding = json.dumps(embedding.tolist())
                
                # For now, just mark as needing update
                # startup.profile_embedding = None  # Will be generated by Flask app
                startup.embedding_updated_at = timezone.now()
                startup.save(update_fields=['embedding_updated_at'])
                count += 1
            
            self.stdout.write(self.style.SUCCESS(f'Processed {count} startups'))
        
        self.stdout.write(self.style.SUCCESS('Embedding generation complete!'))

